{% set name = "helpme" %}
{% set version = "0.0.43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c4ff80595654843a62283c1778c08c115fd8deb55bc684626f2b27bb6b293b38

build:
  number: 7
  entry_points:
    - helpme=helpme.client:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [win or py2k]

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - asciinema >=2.0.1
    - requests

test:
  imports:
    - helpme
    - helpme.client
    - helpme.client.config
    - helpme.client.list
    - helpme.client.help
    - helpme.main
    - helpme.main.base
    - helpme.main.github
    - helpme.main.workers
    - helpme.utils
    - helpme.version
  commands:
    - helpme --help

about:
  home: https://www.github.com/vsoch/helpme
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: a command line client for helping you out
  doc_url: https://vsoch.github.io/helpme
  dev_url: https://github.com/vsoch/helpme

extra:
  recipe-maintainers:
    - vsoch
